# Generated by Django 5.1 on 2024-08-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField(max_length=1024)),
                ("url", models.URLField(max_length=1024)),
                ("ingredients", models.TextField()),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("category", models.CharField(max_length=255)),
                ("skin_tags", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
