# Generated by Django 5.1 on 2024-09-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freya_backend_testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
                ("subscriptionStatus", models.BooleanField()),
                ("skinType", models.CharField(max_length=255)),
                ("photos", models.ImageField(upload_to="photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
